issue script, upgrade module script, new test-module script psql odoo

diff --git a/scripts/upgrade-module b/scripts/upgrade-module
--- a/scripts/upgrade-module
+++ b/scripts/upgrade-module
@@ -1,13 +1,51 @@
 #!/bin/bash
+
+# getopt test
+getopt --test > /dev/null
+if [[ $? -ne 4 ]]; then
+    echo "I’m sorry, `getopt --test` failed in this environment."
+    exit 1
+fi
+
+# prefill default vars based on current folder
 if [ -d "../../../parts" ]; then
   module=${PWD##*/}
+  moduleparm="-u $module"
   odoo=../../../bin/start_odoo
 elif [ $# -eq 0 ]; then
-  echo "Usage: upgrade-module [module-name]"
+  echo "Usage: upgrade-module [-u module] [-d db]"
   exit
 else
-  module=$1
   odoo=bin/start_odoo
 fi
-$odoo --xmlrpc-port=18069 -u $module --stop-after-init
+
+# parse command line options
+OPTIONS=d:u:
+PARSED=$(getopt --options=$OPTIONS --name "$0" -- "$@")
+if [[ $? -ne 0 ]]; then
+    exit 2
+fi
+eval set -- "$PARSED"
+while true; do
+    case "$1" in
+        -d)
+            databaseparm="-d $2"
+            shift 2
+            ;;
+        -u)
+            module="$2"
+            shift 2
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "Programming error."
+            exit 3
+    esac
+done
+
+# upgrade module
+$odoo --xmlrpc-port=18069 --stop-after-init -u $module $databaseparm
 
